changesetIgnorePatterns:
  - "packages/*/test/**"
  - "packages/bindings/npm/**"

initScope: "@solarwinds-apm"
initFields:
  license: Apache-2.0
  publishConfig:
    access: public
    provenance: true

nodeLinker: node-modules
enableGlobalCache: false
npmPublishAccess: public
preferDeferredVersions: true
preferInteractive: true
pnpFallbackMode: none
