changesetIgnorePatterns:
  - packages/*/test/**

enableGlobalCache: false

initFields:
  license: Apache-2.0
  publishConfig:
    access: public
    provenance: true

initScope: "@solarwinds-apm"

nodeLinker: node-modules

npmPublishAccess: public

pnpFallbackMode: none

preferDeferredVersions: true

preferInteractive: true
