packages:
  - packages/*
  - scripts
  - examples
  - examples/*

catalog:
  # The API package should *never* be added as a dependency,
  # always as a peer dependency if it is used
  "@opentelemetry/api": ^1.9.0

  "@opentelemetry/api-logs": ^0.217.0
  "@opentelemetry/semantic-conventions": ~1.40.0

  # Stable SDK components
  "@opentelemetry/core": ^2.7.1
  "@opentelemetry/context-zone": ^2.7.1
  "@opentelemetry/resources": ^2.7.1
  "@opentelemetry/sdk-metrics": ^2.7.1
  "@opentelemetry/sdk-trace-base": ^2.7.1
  "@opentelemetry/sdk-trace-node": ^2.7.1
  "@opentelemetry/sdk-trace-web": ^2.7.1

  # Experimental SDK components
  "@opentelemetry/instrumentation": ^0.217.0
  "@opentelemetry/exporter-logs-otlp-proto": ^0.217.0
  "@opentelemetry/exporter-metrics-otlp-proto": ^0.217.0
  "@opentelemetry/exporter-trace-otlp-proto": ^0.217.0
  "@opentelemetry/instrumentation-grpc": ^0.217.0
  "@opentelemetry/instrumentation-http": ^0.217.0
  "@opentelemetry/opentelemetry-browser-detector": ^0.217.0
  "@opentelemetry/otlp-exporter-base": ^0.217.0
  "@opentelemetry/sdk-logs": ^0.217.0

  "@types/node": ^20.19.0
  eslint: ^9.39.4
  prettier: ^3.8.3
  typescript: ~5.9.3

minimumReleaseAge: 2880 # 2 days
minimumReleaseAgeIgnoreMissingTime: false
minimumReleaseAgeStrict: true
trustPolicy: no-downgrade
blockExoticSubdeps: true

publicHoistPattern:
  - "@types/*"

allowBuilds:
  "@prisma/engines": false
  better-sqlite3: true
  esbuild: false
  prisma: false
  protobufjs: true
  sharp: false
  unrs-resolver: false

trustPolicyExclude:
  - chokidar@4.0.3
  - eslint-import-resolver-typescript@3.10.1
  - semver@6.3.1
  - undici-types@6.21.0
