nodeLinker: node-modules
supportedArchitectures:
  os:
    - linux
  cpu:
    - arm64
    - x64
  libc:
    - glibc
npmScopes:
  solarwinds:
    npmRegistryServer: https://npm.pkg.github.com
    npmAuthToken: ${GITHUB_TOKEN:-GITHUB_TOKEN}
    npmAlwaysAuth: true
