name: Checks
on:
  - push
  - pull_request
  - workflow_dispatch

permissions:
  contents: read
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
      - uses: pnpm/action-setup@v6
        with:
          version: ^11
          cache: true

      - run: pnpm install

      - run: pnpm build -p solarwinds-apm
      - run: pnpm run lint --affected
      - run: pnpm run test --affected
        env:
          SW_APM_COLLECTOR: ${{ secrets.SW_APM_COLLECTOR }}
          SW_APM_SERVICE_KEY: ${{ secrets.SW_APM_SERVICE_KEY }}

      # load bearing .root file
      # actions/upload-artifact will make the archive root the topmost directory which contains all specified files
      # we can force it to be the root of the repo by including an empty file present at the root
      # see https://github.com/actions/upload-artifact#upload-using-multiple-paths-and-exclusions
      - run: touch .root
      - if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v7
        with:
          name: build
          path: |
            .root
            packages/**/dist/
            packages/solarwinds-apm/src/version.ts
          retention-days: 1

  versions:
    if: github.event_name == 'pull_request' && !contains(github.head_ref, 'release')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
      - uses: pnpm/action-setup@v6
        with:
          version: ^11
          cache: true
      - uses: nrwl/nx-set-shas@v5

      - run: pnpm install
      - run: pnpm run version:check

  linux:
    if: github.event_name == 'pull_request'
    needs:
      - checks
    runs-on: ${{ matrix.arch == 'arm64' && 'ubuntu-24.04-arm' || 'ubuntu-24.04' }}
    strategy:
      matrix:
        image:
          - 20-alpine3.20
          - 20-amazonlinux2023
          - 20-debian12
          - 20-ubi8
          - 20-ubuntu22.04
          - 22-alpine
          - 22-amazonlinux
          - 22-debian
          - 22-ubi
          - 22-ubuntu
          - 24-alpine
          - 24-amazonlinux
          - 24-debian
          - 24-ubi
          - 24-ubuntu
        arch:
          - x64
          - arm64
        # https://github.com/actions/runner/issues/801
        exclude:
          - image: 20-alpine3.20
            arch: arm64
          - image: 22-alpine
            arch: arm64
          - image: 24-alpine
            arch: arm64
      fail-fast: false
    container:
      image: ghcr.io/${{ github.repository }}/dev:${{ matrix.image }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v7
      - uses: actions/download-artifact@v8
        with:
          name: build
          path: ./

      - run: pnpm install --ignore-scripts
        continue-on-error: true
      - run: pnpm run test --only --affected
        env:
          SW_APM_COLLECTOR: ${{ secrets.SW_APM_COLLECTOR }}
          SW_APM_SERVICE_KEY: ${{ secrets.SW_APM_SERVICE_KEY }}

  windows:
    if: github.event_name == 'pull_request'
    needs:
      - checks
    runs-on: windows-latest
    strategy:
      matrix:
        node:
          - 20
          - 22
          - 24
      fail-fast: false

    steps:
      - uses: actions/checkout@v7
      - uses: actions/download-artifact@v8
        with:
          name: build
          path: ./
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
      - uses: pnpm/action-setup@v6
        with:
          version: ^11
          standalone: true

      - run: pnpm install --ignore-scripts
        continue-on-error: true
      - run: pnpm run test --only --affected
        env:
          SW_APM_COLLECTOR: ${{ secrets.SW_APM_COLLECTOR }}
          SW_APM_SERVICE_KEY: ${{ secrets.SW_APM_SERVICE_KEY }}

  supports:
    if: github.event_name == 'pull_request'
    needs:
      - checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Include versions from the most recent until the first unsupported
        include:
          # LTS
          - node: 24
            pass: true
          - node: 22
            pass: true
          - node: 20
            pass: true
          - node: 18
            pass: false
          # Unstable
          - node: 23
            pass: false
          # Sanity check
          - node: 8
            pass: false
      fail-fast: false

    steps:
      - uses: actions/checkout@v7
      - uses: actions/download-artifact@v8
        with:
          name: build
          path: ./
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}

      - run: rm package.json && rm pnpm-lock.yaml && npm install --no-save node-releases semver
      - run: node -e "require('assert').ok(${OP} require('${FILE}'))"
        env:
          OP: ${{ !matrix.pass && '!' || '' }}
          FILE: ./packages/solarwinds-apm/dist/commonjs/version.js
