name: Images
on:
  push:
    branches:
      - main
    paths:
      - "docker/*.Dockerfile"
      - ".github/workflows/images.yml"
  workflow_dispatch:

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      matrix:
        image:
          - 20-alpine3.20
          - 20-amazonlinux2023
          - 20-debian12
          - 20-ubi8
          - 20-ubuntu22.04
          - 22-alpine
          - 22-amazonlinux
          - 22-debian
          - 22-ubi
          - 22-ubuntu
          - 24-alpine
          - 24-amazonlinux
          - 24-debian
          - 24-ubi
          - 24-ubuntu
      fail-fast: false

    steps:
      - uses: actions/checkout@v7

      - uses: docker/setup-qemu-action@v4
      - uses: docker/setup-buildx-action@v4
      - uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          context: docker
          file: docker/${{ matrix.image }}.Dockerfile
          platforms: ${{ contains(matrix.image, 'alpine') && 'linux/amd64' || 'linux/amd64,linux/arm64' }}
          push: true
          tags: ghcr.io/${{ github.repository }}/dev:${{ matrix.image }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
