name: Images
on:
  push:
    branches:
      - main
    paths:
      - "docker/*.Dockerfile"
      - ".github/workflows/images.yml"
  workflow_dispatch:

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      matrix:
        image:
          - 20-alpine3.20
          - 20-amazonlinux2023
          - 20-debian12
          - 20-ubi8
          - 20-ubuntu22.04
          - 22-alpine
          - 22-amazonlinux
          - 22-debian
          - 22-ubi
          - 22-ubuntu
          - 24-alpine
          - 24-amazonlinux
          - 24-debian
          - 24-ubi
          - 24-ubuntu
      fail-fast: false

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: docker/setup-qemu-action@1f40c72289eff860ee54a304f1438e3cff362e0a # v4.3.0
      - uses: docker/setup-buildx-action@37fe631027851001ddb9b187196cc803df7f5f0e # v4.3.0
      - uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: docker
          file: docker/${{ matrix.image }}.Dockerfile
          platforms: ${{ contains(matrix.image, 'alpine') && 'linux/amd64' || 'linux/amd64,linux/arm64' }}
          push: true
          tags: ghcr.io/${{ github.repository }}/dev:${{ matrix.image }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
