name: Release
on:
  - workflow_dispatch
jobs:
  publish:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          submodules: true
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: corepack enable

      - run: yarn install --immutable
      - run: yarn lint
      - run: yarn publish
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Export version
        id: version
        run: |
          VERSION=$(cat packages/solarwinds-apm/package.json | jq -r '.version')
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

  lambda:
    needs: publish
    uses: ./.github/workflows/lambda.yml
    with:
      type: testing
      version: ${{ needs.publish.outputs.version }}
    secrets: inherit
