name: Scan packages
on:
  workflow_dispatch:
  workflow_call:
    secrets:
      RLPORTAL_ACCESS_TOKEN:
        required: true

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      RLPORTAL_ACCESS_TOKEN: ${{ secrets.RLPORTAL_ACCESS_TOKEN }}

    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: lts/*
      - uses: pnpm/action-setup@v6
        with:
          version: ^11
          cache: false

      - run: pnpm install
      - run: pnpm run scan
