
---
name: sync secrets
on:   # yamllint disable-line rule:truthy
  push:
    branches:
      - engops_maintenance 
permissions:
  id-token: write
  contents: read
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ vars.GH_APP_ORG_ENGOPS_MAINTENANCE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_SWI_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_ITSANDBOX_SUBSCRIPTION_ID }}
      - name: 'set-org-secret'
        run: |
          echo "Syncing APPLICATION_PRIVATE_KEY ..."
          SECRET="APPLICATION_PRIVATE_KEY"
          SECRET_NAME="solarwinds-apm-js--${SECRET//_/-}"
          [ ! -z "${{ secrets.APPLICATION_PRIVATE_KEY }}" ] && az keyvault secret set --name "$SECRET_NAME" --vault-name "gh-scs" --value "${{ secrets.APPLICATION_PRIVATE_KEY }}"
          echo "Syncing CI_ACCESS_KEY_ID ..."
          SECRET="CI_ACCESS_KEY_ID"
          SECRET_NAME="solarwinds-apm-js--${SECRET//_/-}"
          [ ! -z "${{ secrets.CI_ACCESS_KEY_ID }}" ] && az keyvault secret set --name "$SECRET_NAME" --vault-name "gh-scs" --value "${{ secrets.CI_ACCESS_KEY_ID }}"
          echo "Syncing CI_SECRET_ACCESS_KEY ..."
          SECRET="CI_SECRET_ACCESS_KEY"
          SECRET_NAME="solarwinds-apm-js--${SECRET//_/-}"
          [ ! -z "${{ secrets.CI_SECRET_ACCESS_KEY }}" ] && az keyvault secret set --name "$SECRET_NAME" --vault-name "gh-scs" --value "${{ secrets.CI_SECRET_ACCESS_KEY }}"
          echo "Syncing NPM_TOKEN ..."
          SECRET="NPM_TOKEN"
          SECRET_NAME="solarwinds-apm-js--${SECRET//_/-}"
          [ ! -z "${{ secrets.NPM_TOKEN }}" ] && az keyvault secret set --name "$SECRET_NAME" --vault-name "gh-scs" --value "${{ secrets.NPM_TOKEN }}"
          echo "Syncing TEST_COLLECTOR ..."
          SECRET="TEST_COLLECTOR"
          SECRET_NAME="solarwinds-apm-js--${SECRET//_/-}"
          [ ! -z "${{ secrets.TEST_COLLECTOR }}" ] && az keyvault secret set --name "$SECRET_NAME" --vault-name "gh-scs" --value "${{ secrets.TEST_COLLECTOR }}"
          echo "Syncing TEST_SERVICE_KEY ..."
          SECRET="TEST_SERVICE_KEY"
          SECRET_NAME="solarwinds-apm-js--${SECRET//_/-}"
          [ ! -z "${{ secrets.TEST_SERVICE_KEY }}" ] && az keyvault secret set --name "$SECRET_NAME" --vault-name "gh-scs" --value "${{ secrets.TEST_SERVICE_KEY }}"
